name: Android CI (Debug APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Gradle Build (assembleDebug)
        uses: gradle/gradle-build-action@v3
        with:
         gradle-version: 8.6
         arguments: assembleDebug --stacktrace --info


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quickkeep-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
